export const religion = [
    "African Traditional & Diasporic",
    "Agnostic",
    "Atheist",
    "Baha'i",
    "Buddhism",
    "Cao Dai",
    "Chinese traditional religion",
    "Christianity",
    "Hinduism",
    "Islam",
    "Jainism",
    "Juche",
    "Judaism",
    "Neo-Paganism",
    "Non-religious",
    "Rastafarianism",
    "Secular",
    "Shinto",
    "Sikhism",
    "Spiritism",
    "Tenrikyo",
    "Unitarian-Universalism",
    "Zoroastrianism",
    "Primal-indigenous",
    "Other",
]